title: Python Programming for Humanities 
email: amigcamel@gmail.com
description: >- 
  本課程的設計，希望藉由深入淺出的方式，讓學生在完全沒有程式經驗
  或背景之下也能夠快速上手。並著重於實作及以解決問題的面向，
  讓寫程式變成輔助自身專業知識的基本計算技能之一。
baseurl: "" 
url: "" 
github_username:  amigcamel
github: [metadata]

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker 
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
